version: '3.8'

services:
  playwright-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: playwright-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PLAYWRIGHT_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - CI=true
      - PLAYWRIGHT_BROWSERS_PATH=0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - playwright-network

networks:
  playwright-network:
    driver: bridge
